from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

from src.core.config import Config
from src.core.upload import (
    PageResult,
    TagOperation,
    TagResult,
    UploadResult,
    _MAX_CONSECUTIVE_FAILURES,
    apply_tag_changes,
    build_tree,
    preview_placement,
    process_file,
    upload_pages,
)
from src.core.wiki_client import WikiClientError


class TestProcessFile:
    def test_basic_processing(self, tmp_path: Path) -> None:
        md_file = tmp_path / "page.md"
        md_file.write_text("# My Page\n\nSome content")
        config = Config(base_path="Docs", index_file="README.md")

        result = process_file(
            {"filename": "page.md", "filepath": str(md_file)},
            {},
            config,
        )
        assert result["title"] == "My Page"
        assert result["path"] == "Docs/page"
        assert result["slug"] == "page"
        assert "Some content" in result["content"]

    def test_frontmatter_title(self, tmp_path: Path) -> None:
        md_file = tmp_path / "page.md"
        md_file.write_text("---\ntitle: Custom Title\n---\n\nBody")
        config = Config(base_path="Docs")

        result = process_file(
            {"filename": "page.md", "filepath": str(md_file)},
            {},
            config,
        )
        assert result["title"] == "Custom Title"

    def test_frontmatter_slug(self, tmp_path: Path) -> None:
        md_file = tmp_path / "page.md"
        md_file.write_text("---\nslug: custom-slug\n---\n\nBody")
        config = Config(base_path="Docs")

        result = process_file(
            {"filename": "page.md", "filepath": str(md_file)},
            {},
            config,
        )
        assert result["slug"] == "custom-slug"
        assert result["path"] == "Docs/custom-slug"

    def test_index_file_gets_base_path(self, tmp_path: Path) -> None:
        md_file = tmp_path / "README.md"
        md_file.write_text("# Index\n\nWelcome")
        config = Config(base_path="Docs")

        result = process_file(
            {"filename": "README.md", "filepath": str(md_file)},
            {},
            config,
        )
        assert result["path"] == "Docs"
        assert result["slug"] == ""

    def test_link_rewriting(self, tmp_path: Path) -> None:
        md_file = tmp_path / "page.md"
        md_file.write_text("See [other](other.md) for details.")
        config = Config(base_path="Docs")
        link_map = {"other.md": "/en/Docs/other"}

        result = process_file(
            {"filename": "page.md", "filepath": str(md_file)},
            link_map,
            config,
        )
        assert "/en/Docs/other" in result["content"]

    def test_footer_stripping(self, tmp_path: Path) -> None:
        md_file = tmp_path / "page.md"
        md_file.write_text("# Title\n\nBody\n\n---\nGenerated by tool\n")
        config = Config(
            base_path="Docs",
            strip_footer_patterns=[r"Generated by"],
        )

        result = process_file(
            {"filename": "page.md", "filepath": str(md_file)},
            {},
            config,
        )
        assert "Generated by" not in result["content"]

    def test_filename_fallback_title(self, tmp_path: Path) -> None:
        md_file = tmp_path / "my-page.md"
        md_file.write_text("No heading here, just text.")
        config = Config(base_path="Docs")

        result = process_file(
            {"filename": "my-page.md", "filepath": str(md_file)},
            {},
            config,
        )
        assert result["title"] == "my-page"


class TestUploadPages:
    def _make_client(
        self,
        existing: dict | None = None,
        create_success: bool = True,
        update_success: bool = True,
    ) -> MagicMock:
        client = MagicMock()
        client.check_page_exists.return_value = existing

        create_resp = {
            "data": {
                "pages": {
                    "create": {
                        "responseResult": {
                            "succeeded": create_success,
                            "errorCode": "" if create_success else "error",
                            "message": "" if create_success else "failed",
                        },
                        "page": {"id": 100, "path": "test", "title": "Test"},
                    }
                }
            }
        }
        client.create_page.return_value = create_resp

        update_resp = {
            "data": {
                "pages": {
                    "update": {
                        "responseResult": {
                            "succeeded": update_success,
                            "errorCode": "" if update_success else "error",
                            "message": "" if update_success else "failed",
                        },
                        "page": {"id": 42, "path": "test", "title": "Test"},
                    }
                }
            }
        }
        client.update_page.return_value = update_resp

        return client

    def test_creates_new_page(self) -> None:
        client = self._make_client(existing=None)
        config = Config(locale="en", tags=["test"])
        pages = [{"filename": "page.md", "path": "Docs/page", "title": "Page", "description": "", "content": "Body"}]

        result = upload_pages(client, pages, config)
        assert result.created == 1
        assert result.total == 1
        assert result.pages[0].status == "created"

    def test_skips_existing_without_flag(self) -> None:
        client = self._make_client(existing={"id": 42, "title": "Existing"})
        config = Config(locale="en", update_existing=False)
        pages = [{"filename": "page.md", "path": "Docs/page", "title": "Page", "description": "", "content": "Body"}]

        result = upload_pages(client, pages, config)
        assert result.skipped == 1
        assert result.created == 0

    def test_updates_existing_with_flag(self) -> None:
        client = self._make_client(existing={"id": 42, "title": "Existing"})
        config = Config(locale="en", update_existing=True, tags=[])
        pages = [{"filename": "page.md", "path": "Docs/page", "title": "Page", "description": "", "content": "Body"}]

        result = upload_pages(client, pages, config)
        assert result.updated == 1

    def test_progress_callback_called(self) -> None:
        client = self._make_client(existing=None)
        config = Config(locale="en")
        pages = [
            {"filename": "a.md", "path": "Docs/a", "title": "A", "description": "", "content": "A"},
            {"filename": "b.md", "path": "Docs/b", "title": "B", "description": "", "content": "B"},
        ]

        calls: list[tuple[int, int]] = []
        def callback(current: int, total: int, page: dict) -> None:
            calls.append((current, total))

        upload_pages(client, pages, config, progress_callback=callback)
        assert calls == [(0, 2), (1, 2)]

    def test_cancel_via_callback(self) -> None:
        client = self._make_client(existing=None)
        config = Config(locale="en")
        pages = [
            {"filename": "a.md", "path": "Docs/a", "title": "A", "description": "", "content": "A"},
            {"filename": "b.md", "path": "Docs/b", "title": "B", "description": "", "content": "B"},
        ]

        def cancel_callback(current: int, total: int, page: dict) -> None:
            if current >= 1:
                raise StopIteration

        result = upload_pages(client, pages, config, progress_callback=cancel_callback)
        assert result.total == 1  # Only first page processed


class TestBuildTree:
    def test_basic_tree(self) -> None:
        pages = [
            {"path": "Docs/page1"},
            {"path": "Docs/page2"},
            {"path": "Other/nested/deep"},
        ]
        tree = build_tree(pages)
        assert "Docs" in tree
        assert "Other" in tree
        assert "page1" in tree["Docs"]["_children"]
        assert "page2" in tree["Docs"]["_children"]

    def test_empty_list(self) -> None:
        assert build_tree([]) == {}

    def test_single_page(self) -> None:
        tree = build_tree([{"path": "root"}])
        assert "root" in tree
        assert tree["root"]["_page"]["path"] == "root"


class TestPreviewPlacement:
    def test_marks_new_pages(self) -> None:
        wiki_pages: list[dict] = []
        local_files = [{"filename": "page.md"}]
        tree = preview_placement(wiki_pages, "Docs", local_files, "en")
        assert tree["Docs"]["_children"]["page"]["_label"] == "[NEW]"

    def test_marks_existing_pages(self) -> None:
        wiki_pages = [{"path": "Docs/page", "title": "Page", "locale": "en"}]
        local_files = [{"filename": "page.md"}]
        tree = preview_placement(wiki_pages, "Docs", local_files, "en")
        assert tree["Docs"]["_children"]["page"]["_label"] == "[EXISTS]"


class TestConsecutiveFailureDetection:
    """Test that batch operations stop after consecutive connection failures."""

    def _make_failing_client(self, fail_count: int) -> MagicMock:
        """Client that fails with connection errors for the first N calls."""
        client = MagicMock()
        call_count = {"n": 0}

        def check_page(*args: object, **kwargs: object) -> None:
            call_count["n"] += 1
            if call_count["n"] <= fail_count:
                raise WikiClientError(
                    "Connection error: timeout",
                    is_connection_error=True,
                )
            return None  # page doesn't exist

        client.check_page_exists.side_effect = check_page
        client.create_page.return_value = {
            "data": {
                "pages": {
                    "create": {
                        "responseResult": {"succeeded": True},
                        "page": {"id": 100, "path": "test", "title": "T"},
                    }
                }
            }
        }
        return client

    def test_stops_after_consecutive_connection_failures(self) -> None:
        client = self._make_failing_client(fail_count=10)
        config = Config(locale="en")
        pages = [
            {"filename": f"p{i}.md", "path": f"Docs/p{i}", "title": f"P{i}", "description": "", "content": "B"}
            for i in range(5)
        ]

        result = upload_pages(client, pages, config)
        assert result.stopped_early is True
        assert result.failed == _MAX_CONSECUTIVE_FAILURES
        assert len(result.pages) == _MAX_CONSECUTIVE_FAILURES
        assert "Connection lost" in result.stop_reason

    def test_non_consecutive_failures_continue(self) -> None:
        """If failures are not consecutive (success in between), batch continues."""
        client = MagicMock()
        call_num = {"n": 0}

        def check_page(*args: object, **kwargs: object) -> dict | None:
            call_num["n"] += 1
            # Fail on calls 1, 3 (not consecutive)
            if call_num["n"] in (1, 3):
                raise WikiClientError(
                    "Connection error: timeout",
                    is_connection_error=True,
                )
            return None

        client.check_page_exists.side_effect = check_page
        client.create_page.return_value = {
            "data": {
                "pages": {
                    "create": {
                        "responseResult": {"succeeded": True},
                        "page": {"id": 100, "path": "test", "title": "T"},
                    }
                }
            }
        }
        config = Config(locale="en")
        pages = [
            {"filename": f"p{i}.md", "path": f"Docs/p{i}", "title": f"P{i}", "description": "", "content": "B"}
            for i in range(4)
        ]

        result = upload_pages(client, pages, config)
        assert result.stopped_early is False
        assert result.failed == 2
        assert result.created == 2

    def test_partial_results_returned(self) -> None:
        """When stopped early, partial results are available."""
        client = self._make_failing_client(fail_count=10)
        config = Config(locale="en")
        pages = [
            {"filename": f"p{i}.md", "path": f"Docs/p{i}", "title": f"P{i}", "description": "", "content": "B"}
            for i in range(6)
        ]

        result = upload_pages(client, pages, config)
        # Should have processed exactly _MAX_CONSECUTIVE_FAILURES pages
        assert len(result.pages) == _MAX_CONSECUTIVE_FAILURES
        assert all(p.status == "failed" for p in result.pages)
        assert all(p.is_connection_error for p in result.pages)

    def test_api_errors_dont_trigger_stop(self) -> None:
        """Non-connection failures (API errors) reset the counter."""
        client = MagicMock()
        # All check_page calls fail, but NOT with connection errors
        client.check_page_exists.side_effect = WikiClientError(
            "HTTP 500: Internal Server Error",
            status_code=500,
            is_connection_error=False,
        )
        config = Config(locale="en")
        pages = [
            {"filename": f"p{i}.md", "path": f"Docs/p{i}", "title": f"P{i}", "description": "", "content": "B"}
            for i in range(5)
        ]

        result = upload_pages(client, pages, config)
        assert result.stopped_early is False
        assert result.failed == 5
        assert len(result.pages) == 5


class TestTagChangesConsecutiveFailure:
    def test_stops_after_consecutive_connection_failures(self) -> None:
        client = MagicMock()
        client.update_page_tags.side_effect = WikiClientError(
            "Connection error: timeout", is_connection_error=True
        )
        ops = [
            TagOperation(
                page_id=i, page_path=f"Docs/p{i}", page_title=f"P{i}",
                current_tags=["old"], new_tags=["new"],
            )
            for i in range(5)
        ]

        result = apply_tag_changes(client, ops)
        assert result.stopped_early is True
        assert result.failed == _MAX_CONSECUTIVE_FAILURES
        assert "Connection lost" in result.stop_reason


class TestUploadResult:
    def test_total_property(self) -> None:
        r = UploadResult(created=2, updated=1, skipped=3, failed=1)
        assert r.total == 7

    def test_empty_result(self) -> None:
        r = UploadResult()
        assert r.total == 0
        assert r.pages == []

    def test_stopped_early_defaults(self) -> None:
        r = UploadResult()
        assert r.stopped_early is False
        assert r.stop_reason == ""
