from __future__ import annotations

from src.core.links import build_link_map, rewrite_links, strip_footer_by_patterns


class TestBuildLinkMap:
    def test_basic_mapping(self) -> None:
        files = [
            {"filename": "README.md", "slug": ""},
            {"filename": "page.md", "slug": "page"},
        ]
        link_map = build_link_map(files, "Docs/Project", "en")
        assert link_map["README.md"] == "/en/Docs/Project"
        assert link_map["page.md"] == "/en/Docs/Project/page"

    def test_generates_slug_if_missing(self) -> None:
        files = [{"filename": "01-setup.md"}]
        link_map = build_link_map(files, "Docs", "en")
        assert link_map["01-setup.md"] == "/en/Docs/setup"

    def test_custom_locale(self) -> None:
        files = [{"filename": "page.md", "slug": "page"}]
        link_map = build_link_map(files, "Docs", "nb")
        assert link_map["page.md"] == "/nb/Docs/page"


class TestRewriteLinks:
    def test_rewrites_known_links(self) -> None:
        link_map = {"other.md": "/en/Docs/other"}
        content = "See [Other Page](other.md) for details."
        result = rewrite_links(content, link_map)
        assert result == "See [Other Page](/en/Docs/other) for details."

    def test_leaves_unknown_links(self) -> None:
        link_map = {"known.md": "/en/Docs/known"}
        content = "See [Unknown](unknown.md) page."
        result = rewrite_links(content, link_map)
        assert result == "See [Unknown](unknown.md) page."

    def test_multiple_links(self) -> None:
        link_map = {
            "a.md": "/en/Docs/a",
            "b.md": "/en/Docs/b",
        }
        content = "[A](a.md) and [B](b.md)"
        result = rewrite_links(content, link_map)
        assert result == "[A](/en/Docs/a) and [B](/en/Docs/b)"

    def test_no_links(self) -> None:
        result = rewrite_links("Plain text", {})
        assert result == "Plain text"

    def test_non_md_links_untouched(self) -> None:
        content = "[Link](https://example.com)"
        result = rewrite_links(content, {})
        assert result == content


class TestStripFooterByPatterns:
    def test_strips_matching_footer(self) -> None:
        content = "Body text\n\n---\nGenerated by tool\n"
        result = strip_footer_by_patterns(content, [r"Generated by"])
        assert result == "Body text\n"

    def test_no_match_leaves_content(self) -> None:
        content = "Body text\nFooter line\n"
        result = strip_footer_by_patterns(content, [r"NOMATCH"])
        assert result == "Body text\nFooter line\n"

    def test_empty_patterns(self) -> None:
        content = "Body text\n"
        result = strip_footer_by_patterns(content, [])
        assert result == "Body text\n"

    def test_multiple_patterns(self) -> None:
        content = "Body\n\n---\nPattern A\nPattern B\n"
        result = strip_footer_by_patterns(content, [r"Pattern A", r"Pattern B"])
        assert result == "Body\n"

    def test_case_insensitive(self) -> None:
        content = "Body\nGENERATED BY TOOL\n"
        result = strip_footer_by_patterns(content, [r"generated by"])
        assert result == "Body\n"
